apiVersion: v1
kind: Service
metadata:
  name: softleader-ldap-server
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: ldap-server
  ports:
  - protocol: TCP
    port: 10389