apiVersion: v1
kind: Service
metadata:
  name: softleader-ldap-server-publish
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: ldap-server
  ports:
  - protocol: TCP
    port: 10389
    nodePort: {{ .Values.service.ldapServer.nodePort }}